# This requires docker-compose 1.6.0
version: '2'
services:
  rtpproxy:
    build: .
    network_mode: host
    command: /kamailio.sh rtpproxy
  kamailio:
    build: .
    network_mode: host
    environment:
      SIP_DOMAIN: sip.example.com
    command: /kamailio.sh
